language: node_js
node_js:
  - 15
cache:
    directories:
      - node_modules
before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - rm -rf aws*
  - export PATH=$PATH:$HOME/.local/bin
  - sudo apt-get install jq
install:
  - npm install
jobs:
  include:
    - stage: 'lint'
      name: 'Lint'
      script: npm run lint
    - stage: 'test'
      name: 'Test'
      script: npm run test
    - stage: 'build'
      name: 'Build'
      script: npm run build
    - stage: 'store'
      name: 'store in S3'
      script:
        - bash deploy/scripts/create-bucket.sh
        - aws s3api cp build base-web-client/build
env:
  global:
    - BUCKET_NAME=base-web-client
matrix:
  fast_finish: true




