language: node_js
node_js:
- 15
cache:
  directories:
  - node_modules
before_install:
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
- rm -rf aws*
- export PATH=$PATH:$HOME/.local/bin
- sudo apt-get install jq
install:
- npm install
jobs:
  include:
    - stage: lint
      name: Lint
      script: npm run lint
    - stage: test
      name: Test
      script: npm run test
    - stage: build
      name: Build
      script: npm run build
    - stage: store
      name: store in S3
      script:
      - bash deploy/scripts/create-bucket.sh
      - aws s3 cp --recursive build ${BUCKET_NAME}/base-web-client/build
env:
  global:
  - BUCKET_NAME=shubh-react-apps
  - secure: jW4mUn0E/NmtpUQXkArE3W3zBMf3xpJw/yKPzCirLWkLNcV9qPOEFBzzj/Zj6xjJH3wxwms/IvEG+gxQ51c5fGLUotb2wfEPGd8v6On2zF2OclToTP1YhmCHwaHXGkPquex6Dk366l1i06IiGXZVHRpLFIb0CSpbCmaYvYbRdwNlLWijsVNbO+6wK1qRLa6lqp1QcEqqkFcYdwV7cdYNzOzUZV7zouBgW274aWffKxFa7xVhyyFNEQMFpzQoGS2aBzV0vUAa8v/GM9Woq3lbPdFyEFH+sV/ywP0Pren0BlCxoRVjJUoYM8MzSljL0NTdGxDi/m93BAaPdVbew1FvvYBG0IScjzaLHmGvWdwZvAJakEZ3O7GfK3Ws91/Aji44C9yv9wvvQWYrfvvRl8gZTyuEMzMNwnoOzPMP/eKitLbv1fLY569k9IzSOR86QTwxYJtba8vK9uHhn2coVQAne37NUGEfbFj14EcjnJZP1C5lOizFpJ7TPT1c+LBlRL+UJfJtDqxxT3LpiCI7wxC0yY9vfiXbJuUdaFrfD30/g1G9G2TgyhlRfOIyS9Kg9IDMZaCnMihuZ5MAK0EUg3Mb4dfZ9TKpfHZJfQ37LNQO8AgGwGhjipUUbyGZMA0TgMwnvzURgIAUosWunTW0vqPtZMt+ki8y6L1jBlZp6RFKYCU=
  - secure: lfqo88X4kMV7GFmNSwUT1IrfNdG5x8zw7SumaaLIYjMQWqVGvys5RKfur7oC5Be1TjC8duD4XuQ4YfSMzhgD5ALn/CQh8u/YwIIbXFruV+1IV1WbStdswYQbj0bsRvWHAzO7CDTZBKJ4ZLMhIfgJ+X8AwbvCgzfhbb4g0wdTHPzqm85ovnEC/pLa3y0HfJhxvXFWNLPoopc+K5PgYMnikS1tc0mpYbntj6zsIas0d5m4hKSYXBPeeaOsBRpAQ+oyAhg8JpGvfOX9iGGbpjFTI0ioaM+HjL2AXwvUqZdavlWQK332pLcGPq6Aobd0e7PCt53DcBOBRz2l+jsr+jwUcmuwk1WiWpqwv71Mdvk7Jx/cGjhR8LkkZaFElY/99BovgO1FM7FrDJtcL15ZVdciB7flnihKBSdTrxJX3U5GRyYsil+NCocVOvF0iX+6d0SYZHlK42esN6x4geK+rmeiVZmxO7gNmm7W1X01EUFphB+KQSAZ1raOCbJV03/tUoHe5vx6n097u+/BDrV8I0sh3Hh2YCbc57Q9M9jF6q+lYzhJqCUlem2qt7dQWto+PaqBBqbojeB7U58vPwz7RBPcTNIinlQNbCIhJXceH2MhBePRjUqgMCzimoak/Aspn8YFkRbl68n/cHctyvwTTKuiZ/8EobQYToUcK2aQOIDsrRY=
matrix:
  fast_finish: true
